### ISSUE TITLE
Maintenance info version must be a Semantic Version

### ISSUE THREAD

**Issue by patrickcrocker** [cloudfoundry/overview-broker#27]
The recent changes to [add maintenance info support](https://github.com/cloudfoundry/overview-broker/commit/d6bde25f6a408b6dbf659b3610624b3ab8320e2a) are resulting in a Semantic Version error:

```
$ cf version
cf version 6.47.2+d526c2cb3.2019-11-05

$ cf target
api endpoint:   https://api.run.nulldriver.com
api version:    2.139.0
user:           admin
org:            cfclitest Org 8kl4b3BOMW
space:          cfclitest Space 8kl4b3BOMW

$ cf create-service-broker 'cfclitest Space Scoped Broker 8kl4b3BOMW' admin password https://cfclitest-space-scoped-broker-8kl4b3bomw.cfapps.nulldriver.com --space-scoped
  Creating service broker cfclitest Space Scoped Broker 8kl4b3BOMW in org cfclitest Org 8kl4b3BOMW / space cfclitest Space 8kl4b3BOMW as admin...
  Service broker catalog is invalid: 
  Service overview-service
    Plan small
      Maintenance info version must be a Semantic Version, but has value "v1.0"
    Plan large
      Maintenance info version must be a Semantic Version, but has value "v1.0"
  
  FAILED
```

If I use the previous version of overview-broker before that commit, everything works fine.

**Comment by mattmcneeney** [comment]
Hey @patrickcrocker 

Thanks for pointing this out. A pipeline failure went unnoticed!

This is now fixed on the master branch: https://github.com/cloudfoundry/overview-broker/commit/931266c4929d19a42afcbe817bc70d6abafaf2bf

Let us know if anything else goes wrong!
